#include "core/audio/soundfont_synth.h"

#define TSF_IMPLEMENTATION
#include <tsf.h>

#include "soundfont_path.h"  // generated by CMake -- kBundledSoundFontPath

#include <algorithm>

namespace zeebulator {

namespace {

// Real GM channel 10 (0-indexed 9) is the fixed real percussion
// channel -- tsf_channel_set_presetnumber's own `flag_mididrums`
// argument tells it to look in the real soundfont's drum bank (128)
// for that channel instead of the melodic bank.
constexpr int kPercussionChannel = 9;

struct MidiEvent {
  double time_seconds;
  bool is_note_on;
  int channel;
  int note;
  int program;
  int velocity;
};

}  // namespace

SoundFontSynth::SoundFontSynth() : synth_(tsf_load_filename(kBundledSoundFontPath)) {}

SoundFontSynth::~SoundFontSynth() {
  if (synth_ != nullptr) tsf_close(synth_);
}

std::vector<int16_t> SoundFontSynth::RenderMidi(const MidiFile& midi, int sample_rate) {
  if (synth_ == nullptr || midi.notes.empty() || midi.division <= 0) return {0};

  std::vector<MidiEvent> events;
  events.reserve(midi.notes.size() * 2);
  for (const MidiNote& n : midi.notes) {
    double start_s = TickToSeconds(n.start_tick, midi.division, midi.tempo_changes);
    double end_s = TickToSeconds(n.end_tick, midi.division, midi.tempo_changes);
    if (end_s <= start_s) continue;
    events.push_back({start_s, true, n.channel, n.note, n.program, n.velocity});
    events.push_back({end_s, false, n.channel, n.note, n.program, 0});
  }
  if (events.empty()) return {0};
  // Note Offs before Note Ons at the same real timestamp -- releasing a
  // real note a moment before a new one starts (rather than after)
  // avoids briefly exceeding real polyphony/voice-stealing behavior on
  // simultaneous boundary events.
  std::stable_sort(events.begin(), events.end(), [](const MidiEvent& a, const MidiEvent& b) {
    if (a.time_seconds != b.time_seconds) return a.time_seconds < b.time_seconds;
    return a.is_note_on < b.is_note_on;
  });

  double total_seconds = events.back().time_seconds;
  size_t total_samples = static_cast<size_t>(total_seconds * sample_rate) + 1;
  std::vector<int16_t> out(total_samples, 0);

  // Real headroom: a real, dense multi-channel performance (Double
  // Dragon's own real background music uses up to 9 simultaneous real
  // channels, PHASE8_LOG.md's "Sound, round twelve") pushed
  // TinySoundFont's own internal mix to real, measured, confirmed-live
  // clipping (peak pinned at the exact int16 ceiling) at 0dB, drowning
  // out real, much quieter WAV-based SFX voices in the shared Mixer
  // once real gameplay music was actually reachable to listen to
  // (round thirteen). `global_gain_db` is TinySoundFont's own real
  // mechanism for this -- reducing gain here (before summing/clipping
  // happens inside tsf's own render) actually prevents the clipping,
  // unlike a post-render scale-down which can only turn down audio
  // that's already been distorted.
  // -16dB rather than -15dB per the user's own live A/B comparison
  // against the real thing (~10% quieter in linear amplitude terms --
  // 20*log10(0.9) is ~-0.9dB).
  constexpr float kHeadroomDb = -16.0f;
  tsf_reset(synth_);
  tsf_set_output(synth_, TSF_MONO, sample_rate, kHeadroomDb);

  size_t rendered = 0;
  for (const MidiEvent& e : events) {
    size_t event_sample = std::min(static_cast<size_t>(e.time_seconds * sample_rate), total_samples);
    if (event_sample > rendered) {
      int chunk = static_cast<int>(event_sample - rendered);
      tsf_render_short(synth_, out.data() + rendered, chunk, 0);
      rendered += static_cast<size_t>(chunk);
    }
    if (e.is_note_on) {
      tsf_channel_set_presetnumber(synth_, e.channel, e.program, e.channel == kPercussionChannel);
      tsf_channel_note_on(synth_, e.channel, e.note, std::clamp(e.velocity, 0, 127) / 127.0f);
    } else {
      tsf_channel_note_off(synth_, e.channel, e.note);
    }
  }
  if (rendered < total_samples) {
    tsf_render_short(synth_, out.data() + rendered, static_cast<int>(total_samples - rendered), 0);
  }
  return out;
}

}  // namespace zeebulator
